name: push

on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./...

  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=proto/idl'

  build-publish:
    runs-on: ubuntu-latest
    needs: [ buf, test ]
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # build model, build binary
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: create model
        run: go run cmd/train/main.go
      - run: mv theta.bin svc/models/theta.bin

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: trelore/iris-classification:latest